spring.application.name=wheather


spring.datasource.url=jdbc:postgresql://localhost:5432/WheatherApp
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
#logging.level.org.springframework = debug 

spring.security.user.name=chintu
spring.security.user.password=chintu@123
